export const MOBILE_NUMBER_CHANGED = 'MOBILE_NUMBER_CHANGED'
export const OTP_CHANGED = 'OTP_CHANGED'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOADING = 'loading'
export const CONFIRM_MOBILE = 'CONFIRM_MOBILE'